#!/usr/bin/env bash
set -e -o pipefail

cur_dir="$(cd "$(dirname "$0")" && pwd)"
cd "$cur_dir"
source "$cur_dir/.dev/common.sh"

"$dev_env/bin/flask" run &
server_pid="$!"
sleep 1

proc_status="$(ps "$server_pid")"
if [[ -z "$proc_status" ]]; then
    exit 1
fi

web_port=5000
test_auth_token="$(cat "$cur_dir/.dev/test-auth-token.txt")"
test_vars="{
    'test_auth_token': '$test_auth_token',
    'web_port': '$web_port',
}"

"$dev_env/bin/python" "$cur_dir/.dev/manage-db.py" setup

set +e
"$dev_env/bin/pyresttest" "http://127.0.0.1:$web_port" endpoint-specs.yml --vars="$test_vars"
result="$?"
set -e

kill "$server_pid"
"$dev_env/bin/python" "$cur_dir/.dev/manage-db.py" tear-down

exit "$result"
