#!/usr/bin/env bash
set -e -o pipefail

cd "$(dirname "$0")"

cpu_count="$(getconf _NPROCESSORS_ONLN)"
worker_count="$(($cpu_count * 2))"

uwsgi --http '0.0.0.0:5000' \
    --workers "$worker_count" \
    --master \
    --disable-logging \
    --no-orphans \
    --wsgi-file api.py \
    --callable app
