- hosts: sms487
  become: true
  vars:
    docker_registry_url: "{{ lookup('ansible.builtin.env', 'DOCKER_REGISTRY_URL') }}"
    app_docker_image: "{{ lookup('ansible.builtin.env', 'APP_DOCKER_IMAGE') + ':' + lookup('ansible.builtin.env', 'APP_DOCKER_TAG') }}"
    docker_yandex_cloud_login: true
    internal_port: 5000
    project_environment:
      - DEPLOY_TYPE=yc
      - LOG_LEVEL=INFO
      - TZ_OFFSET=3
      - START_URL=/
      - AUTH_BASE_URL={{ auth_base_url }}
      - YC_METADATA_SERVICE=169.254.169.254
      - MONGO_HOSTS=mongodb
      - MONGO_PORT=27017
      - MONGO_DB_NAME=sms487

  roles:
    - https-site
    - docker-compose-project
