#!/usr/bin/env bash
set -ex -o pipefail

cur_dir="$(cd "$(dirname "$0")" && pwd)"
project_dir="$cur_dir/.."
cd "$project_dir"

"$cur_dir/docker-build"
"$cur_dir/docker-test"
"$cur_dir/docker-push"

ansible-playbook -i ~/.private/ansible-inventory.yml "$cur_dir/setup.yml"
